export function VideoFeed() {
  return (
    <div className="bg-black aspect-video w-full max-w-4xl rounded-lg shadow-lg overflow-hidden">
      <video className="w-full h-full object-cover" autoPlay playsInline muted />
      {/* The video element is muted by default to prevent audio feedback. Sound will be generated by Tone.js. */}
    </div>
  );
}