import { type RefObject } from 'react';

interface VideoFeedProps {
  videoRef: RefObject<HTMLVideoElement | null>;
}

export function VideoFeed({ videoRef }: VideoFeedProps) {
  return (
    <div className="bg-black aspect-video w-full max-w-4xl rounded-lg shadow-lg overflow-hidden">
      <video
        ref={videoRef}
        className="w-full h-full object-cover"
        autoPlay
        playsInline
        muted
      />
      {/* The video element is muted by default to prevent audio feedback. Sound is generated by Tone.js. */}
    </div>
  );
}